### PR TITLE
add now/retrig and make the prompt (and prompt2 for multiline things)…

### PR DESCRIPTION
**Pull request by yaxu**
… silent. a good idea?

### CODE REVIEW

**Comment by kindohm** [comment]
giving it a spin...

**Comment by kindohm** [comment]
Hrm, `retrig` doesn't seem to work for me. Doesn't `retrig` need to be reset every time you want to use it? That's the only way I can get it to work. Like this:

```
do  
    now' <- getNow
    let now = nextSam now'
    let retrig = (now `rotR`)
    d1 $ retrig $ slowcat [ 
        sound "bd*8", 
        sound "feel:2*6", 
        sound "ul(5,8)", 
        sound "cp*8",
        s "arpy*5" # n (run 30),
        sound "bass(3,8)" ]
```

**Comment by kindohm** [comment]
As for the silent prompt, I kind of miss the feedback that ghci received my command. Maybe we could make it a configurable option to make the prompt silent or not. I don't know what the default should be though.

**Comment by telephon** [comment]
if the prompts had newlines at the end they would be more readable in general.

**Comment by mhodnick-spok** [comment]
In lieu of the open conversation on this PR, @yaxu for future reference you don't need to manually increment the version in `package.json`. The Atom package manager `apm` automatically increments the version in package.json and performs a commit/push when publishing.

**Comment by ndr-brt** [comment]
is this PR still valuable?

**Comment by yaxu** [comment]
No, this is all out of date. All the plugins should more or less have the same BootTidal.hs now

**Pull request closed without merging**
