### PR TITLE
Add github actions definition

### PR DESCRIPTION
**Pull request by ndr-brt**
Ref. #142

### CODE REVIEW

**Comment by yaxu** [comment]
Nice, I guess we should do this for tidal too?

**Comment by ndr-brt** [comment]
Don't know, I read some things about travis changing policies etc...
But I'm finding this way faster and easier to check (same platform).

At the moment I have some problems making the test executing, but I think the problem is with the "not-so-good" atom packages toolkit (atom+apm commands)

**Comment by ndr-brt** [comment]
Correct myself, the tests are running but no "human readable" output (just one dot for every test...)

**Comment by ndr-brt** [comment]
Would be interesting investigate also the possibility to define the publish process as an action

**Pull request merged**
